"""Processing-layer data contracts — outputs of modal processors."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from openrag.models.content import ContentBlock, ContentPayload


class EntityType(str, Enum):
    """Ontology of entity types recognised by OpenRAG."""

    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"
    LOCATION = "LOCATION"
    CONCEPT = "CONCEPT"
    ALGORITHM = "ALGORITHM"
    DATASET = "DATASET"
    EQUATION = "EQUATION"
    FUNCTION = "FUNCTION"
    CLASS = "CLASS"
    MODULE = "MODULE"
    PRODUCT = "PRODUCT"
    EVENT = "EVENT"
    UNKNOWN = "UNKNOWN"


@dataclass
class EntityCandidate:
    """A named entity tentatively extracted from a content block."""

    name: str
    """Surface form of the entity."""

    canonical_name: str
    """Normalised / lowercased form used for deduplication."""

    entity_type: EntityType
    confidence: float = 1.0
    source_text: str | None = None
    """Sentence or phrase from which this entity was extracted."""


@dataclass
class ContextWindowConfig:
    """Configuration for the Context Enricher."""

    strategy: str = "page_window"
    """One of: page_window | block_window | section_ancestor | semantic_neighbour"""

    window_size: int = 2
    """Number of pages/blocks before and after the target block."""

    max_tokens: int = 1500
    """Hard cap on context length (in tokens)."""

    include_captions: bool = True
    """Whether to prepend image/table captions as context."""

    filter_types: list[str] = field(default_factory=lambda: ["text"])
    """Block types eligible as context sources."""


@dataclass
class ProcessingContext:
    """
    Runtime context passed to every modal processor during pipeline execution.

    Carries references to the full document payload (for context extraction),
    the configured AI model callables, and per-run config.
    """

    payload: ContentPayload
    """The entire document being processed."""

    llm_func: Callable[..., Any]
    """Text LLM callable: async fn(prompt: str, **kwargs) -> str"""

    vlm_func: Callable[..., Any] | None
    """Vision LLM callable: async fn(prompt: str, image_b64: str, **kwargs) -> str"""

    context_config: ContextWindowConfig
    tenant_id: str
    namespace: str
    extra: dict[str, Any] = field(default_factory=dict)
    """Arbitrary per-pipeline config values forwarded to processors."""


@dataclass
class ProcessedBlock:
    """
    Enriched output produced by a modal processor for a single ContentBlock.

    This is the unit consumed by the Knowledge Layer (embedding engine,
    KG builder, BM25 indexer).
    """

    source_block: ContentBlock
    """Original block this was derived from."""

    natural_language_description: str
    """Human-readable description/caption generated by the AI model."""

    embedding_text: str
    """Text string that will be sent to the embedding model.
    Typically = description + any extracted OCR/table text."""

    embedding: list[float] | None = None
    """Dense vector representation of the block (populated by EmbeddingEngine)."""

    @property
    def document_id(self) -> str:
        return self.source_block.document_id

    @property
    def block_id(self) -> str:
        return self.source_block.block_id

    @property
    def block_type(self) -> BlockType:
        return self.source_block.block_type

    @property
    def content(self) -> str:
        return self.embedding_text

    @property
    def page_number(self) -> int | None:
        return self.source_block.page_number

    @property
    def index(self) -> int:
        return self.source_block.sequence_index

    entity_candidates: list[EntityCandidate] = field(default_factory=list)
    """Named entities tentatively extracted from description + context."""

    structured_data: Any | None = None
    """
    Optional modality-specific structure:
    - Table:    list[dict]  (rows as dicts of column→value)
    - Equation: dict        {latex, simplified, domain}
    - Code:     dict        {functions: [], classes: [], imports: []}
    - Audio:    list[dict]  [{start, end, text, speaker}]
    """

    confidence_score: float = 1.0
    """Model confidence in the generated description (0.0–1.0)."""

    processing_metadata: dict[str, Any] = field(default_factory=dict)
    """Diagnostic info: model_name, latency_ms, prompt_tokens, etc."""
